try {
    throw Exception("Caught Exception");
} catch ($error) {
    echo $error->toString();
}